export type Sport = string;

export type Coach = {
  id: string;
  name: string;
  location: string;
  sports: Sport[];
  tags: string[];
  specialty: string;
  rating: number | null;
  reviewCount: number;
  price: number;
  reason: string;
  badge: string;
  mode: "In person" | "Online" | "In person + Online";
  offersOnline: boolean;
  offersInPerson: boolean;
  area: string;
  coordinates: [longitude: number, latitude: number] | null;
  availability: string[];
  image: string | null;
  avatar?: string | null;
  adImages?: string[];
  rank: number;
  bio: string;
  experience: string;
  credentials: string[];
  coachingStyle: string;
  languages: string[];
  lessonCount: number;
  audiences: string[];
  levels: string[];
  lessonPlan: Array<{ title: string; description: string }>;
  isDemo?: boolean;
  faqs: Array<{ question: string; answer: string }>;
};

type BaseCoach = Omit<Coach, "tags" | "offersOnline" | "offersInPerson" | "area" | "coordinates" | "bio" | "experience" | "credentials" | "coachingStyle" | "languages" | "lessonCount" | "audiences" | "levels" | "lessonPlan" | "faqs">;

const baseCoaches: BaseCoach[] = [
  {
    id: "ayesha-khan",
    name: "Ayesha Khan",
    location: "Lahore",
    sports: ["Cricket"],
    specialty: "Beginner batting technique",
    price: 3500,
    mode: "In person",
    availability: ["Saturday", "Sunday"],
    rating: null,
    reviewCount: 0,
    reason: "Patient batting fundamentals and repeatable practice routines.",
    image: null,
    badge: "Demo profile",
    rank: 1,
  },
  {
    id: "hamza-siddiqui",
    name: "Hamza Siddiqui",
    location: "Karachi",
    sports: ["Tennis", "Badminton"],
    specialty: "Serve consistency and match confidence",
    price: 4200,
    mode: "In person",
    availability: ["Friday", "Saturday"],
    rating: null,
    reviewCount: 0,
    reason: "Reliable movement, clean contact, and practical match decisions.",
    image: null,
    badge: "Demo profile",
    rank: 2,
  },
  {
    id: "sara-ahmed",
    name: "Sara Ahmed",
    location: "Online",
    sports: ["Yoga"],
    specialty: "Flexible online yoga foundations",
    price: 2500,
    mode: "Online",
    availability: ["Monday", "Wednesday", "Sunday"],
    rating: null,
    reviewCount: 0,
    reason: "Accessible mobility, balance, and sustainable movement sessions.",
    image: null,
    badge: "Demo profile",
    rank: 3,
  },
  {
    id: "zainab-malik",
    name: "Zainab Malik",
    location: "Lahore",
    sports: ["Swimming"],
    specialty: "Confident swimming fundamentals",
    price: 4000,
    mode: "In person",
    availability: ["Tuesday", "Thursday", "Saturday"],
    rating: null,
    reviewCount: 0,
    reason: "Safe breathing, body position, and efficient stroke development.",
    image: null,
    badge: "Demo profile",
    rank: 4,
  },
  {
    id: "omar-farooq",
    name: "Omar Farooq",
    location: "Online",
    sports: ["Strength"],
    specialty: "Online strength training for beginners",
    price: 2800,
    mode: "Online",
    availability: ["Monday", "Thursday", "Saturday"],
    rating: null,
    reviewCount: 0,
    reason: "Equipment-aware strength sessions with manageable weekly progress.",
    image: null,
    badge: "Demo profile",
    rank: 5,
  },
  {
    id: "bilal-raza",
    name: "Bilal Raza",
    location: "Lahore",
    sports: ["Football"],
    specialty: "Football skills and decision making",
    price: 3800,
    mode: "In person",
    availability: ["Friday", "Saturday", "Sunday"],
    rating: null,
    reviewCount: 0,
    reason: "First touch, positioning, and realistic small-sided decisions.",
    image: null,
    badge: "Demo profile",
    rank: 6,
  },
  {
    id: "danish-iqbal",
    name: "Danish Iqbal",
    location: "Karachi",
    sports: ["Boxing"],
    specialty: "Boxing fitness and fundamentals",
    price: 3600,
    mode: "In person",
    availability: ["Tuesday", "Thursday", "Sunday"],
    rating: null,
    reviewCount: 0,
    reason: "Controlled technique, coordination, and conditioning fundamentals.",
    image: null,
    badge: "Demo profile",
    rank: 7,
  },
  {
    id: "hira-noor",
    name: "Hira Noor",
    location: "Lahore",
    sports: ["Badminton"],
    specialty: "Badminton movement and control",
    price: 3000,
    mode: "In person",
    availability: ["Wednesday", "Saturday"],
    rating: null,
    reviewCount: 0,
    reason: "Court movement, controlled strokes, and rally confidence.",
    image: null,
    badge: "Demo profile",
    rank: 8,
  },
  {
    id: "farhan-akram",
    name: "Farhan Akram",
    location: "Islamabad",
    sports: ["Running"],
    specialty: "Endurance running structure",
    price: 4500,
    mode: "In person + Online",
    availability: ["Tuesday", "Friday", "Sunday"],
    rating: null,
    reviewCount: 0,
    reason: "Sensible pacing, consistent training habits, and event preparation.",
    image: null,
    badge: "Demo profile",
    rank: 9,
  },
  {
    id: "mariam-shah",
    name: "Mariam Shah",
    location: "Karachi",
    sports: ["Basketball"],
    specialty: "Basketball handling and shooting",
    price: 3400,
    mode: "In person",
    availability: ["Friday", "Saturday"],
    rating: null,
    reviewCount: 0,
    reason: "Ball control, shooting mechanics, and game-speed decisions.",
    image: null,
    badge: "Demo profile",
    rank: 10,
  },
  {
    id: "usman-tariq",
    name: "Usman Tariq",
    location: "Lahore",
    sports: ["Table Tennis"],
    specialty: "Table tennis consistency",
    price: 3200,
    mode: "In person",
    availability: ["Monday", "Thursday", "Saturday"],
    rating: null,
    reviewCount: 0,
    reason: "Serve quality, rally stability, and purposeful match patterns.",
    image: null,
    badge: "Demo profile",
    rank: 11,
  },
  {
    id: "nadia-hussain",
    name: "Nadia Hussain",
    location: "Online",
    sports: ["Yoga", "Strength"],
    specialty: "Gentle online mobility sessions",
    price: 2200,
    mode: "Online",
    availability: ["Monday", "Wednesday", "Friday"],
    rating: null,
    reviewCount: 0,
    reason: "Approachable mobility routines with clear movement options.",
    image: null,
    badge: "Demo profile",
    rank: 12,
  },
  {
    id: "rida-aslam",
    name: "Rida Aslam",
    location: "Online",
    sports: ["Cricket"],
    specialty: "Online cricket analysis and batting plans",
    price: 2700,
    mode: "Online",
    availability: ["Tuesday", "Thursday", "Sunday"],
    rating: null,
    reviewCount: 0,
    reason: "Clip-led batting decisions and actionable practice priorities.",
    image: null,
    badge: "Demo profile",
    rank: 13,
  },
  {
    id: "sameer-qureshi",
    name: "Sameer Qureshi",
    location: "Karachi",
    sports: ["Football", "Strength"],
    specialty: "Football conditioning and movement",
    price: 3900,
    mode: "In person",
    availability: ["Wednesday", "Friday", "Sunday"],
    rating: null,
    reviewCount: 0,
    reason: "Ball work, movement quality, and adjustable conditioning.",
    image: null,
    badge: "Demo profile",
    rank: 14,
  },
  {
    id: "iqra-javed",
    name: "Iqra Javed",
    location: "Islamabad",
    sports: ["Tennis"],
    specialty: "Tennis fundamentals and rally confidence",
    price: 3100,
    mode: "In person",
    availability: ["Friday", "Saturday", "Sunday"],
    rating: null,
    reviewCount: 0,
    reason: "Movement, clean contact, and confidence in longer rallies.",
    image: null,
    badge: "Demo profile",
    rank: 15,
  },
  {
    id: "haris-mehmood",
    name: "Haris Mehmood",
    location: "Islamabad",
    sports: ["Cricket"],
    specialty: "Bowling control and match plans",
    rating: null,
    reviewCount: 0,
    price: 3300,
    reason: "Structured cricket coaching for bowling accuracy and practical match planning.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Tuesday", "Saturday"],
    image: null,
    rank: 16,
  },
  {
    id: "sana-rauf",
    name: "Sana Rauf",
    location: "Lahore",
    sports: ["Tennis"],
    specialty: "Rally foundations and court movement",
    rating: null,
    reviewCount: 0,
    price: 3200,
    reason: "Supportive tennis sessions for steadier rallies and confident court movement.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Wednesday", "Sunday"],
    image: null,
    rank: 17,
  },
  {
    id: "ahmed-nawaz",
    name: "Ahmed Nawaz",
    location: "Online",
    sports: ["Strength"],
    specialty: "Home strength and movement basics",
    rating: null,
    reviewCount: 0,
    price: 2400,
    reason: "Simple online strength coaching adapted to limited space and equipment.",
    badge: "Demo profile",
    mode: "Online",
    availability: ["Monday", "Thursday"],
    image: null,
    rank: 18,
  },
  {
    id: "mehwish-iqbal",
    name: "Mehwish Iqbal",
    location: "Islamabad",
    sports: ["Swimming"],
    specialty: "Breathing rhythm and stroke confidence",
    rating: null,
    reviewCount: 0,
    price: 4100,
    reason: "Calm pool coaching for breathing control, body position and confident strokes.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Friday", "Sunday"],
    image: null,
    rank: 19,
  },
  {
    id: "talha-ansari",
    name: "Talha Ansari",
    location: "Rawalpindi",
    sports: ["Football"],
    specialty: "First touch and passing decisions",
    rating: null,
    reviewCount: 0,
    price: 3500,
    reason: "Game-based football coaching for cleaner first touch and smarter passing choices.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Friday", "Saturday"],
    image: null,
    rank: 20,
  },
  {
    id: "kiran-shah",
    name: "Kiran Shah",
    location: "Karachi",
    sports: ["Badminton"],
    specialty: "Court coverage and rally control",
    rating: null,
    reviewCount: 0,
    price: 3100,
    reason: "Friendly badminton coaching for efficient movement and longer controlled rallies.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Tuesday", "Saturday"],
    image: null,
    rank: 21,
  },
  {
    id: "saad-mirza",
    name: "Saad Mirza",
    location: "Islamabad",
    sports: ["Basketball"],
    specialty: "Ball handling and finishing",
    rating: null,
    reviewCount: 0,
    price: 3600,
    reason: "Focused basketball sessions for stronger handles and composed finishing at the rim.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Wednesday", "Sunday"],
    image: null,
    rank: 22,
  },
  {
    id: "anum-tariq",
    name: "Anum Tariq",
    location: "Online",
    sports: ["Yoga"],
    specialty: "Mobility and desk-work recovery",
    rating: null,
    reviewCount: 0,
    price: 2100,
    reason: "Accessible online movement sessions for mobility, balance and everyday comfort.",
    badge: "Demo profile",
    mode: "Online",
    availability: ["Monday", "Wednesday", "Friday"],
    image: null,
    rank: 23,
  },
  {
    id: "waleed-khan",
    name: "Waleed Khan",
    location: "Lahore",
    sports: ["Boxing"],
    specialty: "Defense, balance and controlled combinations",
    rating: null,
    reviewCount: 0,
    price: 3700,
    reason: "Technique-first boxing coaching for stance, defense and controlled combinations.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Thursday", "Sunday"],
    image: null,
    rank: 24,
  },
  {
    id: "komal-aziz",
    name: "Komal Aziz",
    location: "Lahore",
    sports: ["Running"],
    specialty: "5K pacing and sustainable endurance",
    rating: null,
    reviewCount: 0,
    price: 2800,
    reason: "Practical running coaching for steadier pacing and manageable 5K preparation.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Tuesday", "Sunday"],
    image: null,
    rank: 25,
  },
  {
    id: "rehan-malik",
    name: "Rehan Malik",
    location: "Rawalpindi",
    sports: ["Table Tennis"],
    specialty: "Serve variation and spin reading",
    rating: null,
    reviewCount: 0,
    price: 3000,
    reason: "Technical table-tennis sessions for serve variety, spin reading and rally patterns.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Monday", "Saturday"],
    image: null,
    rank: 26,
  },
  {
    id: "alina-qureshi",
    name: "Alina Qureshi",
    location: "Online",
    sports: ["Cricket"],
    specialty: "Remote batting review and practice plans",
    rating: null,
    reviewCount: 0,
    price: 2600,
    reason: "Online cricket analysis that turns player clips into focused batting practice.",
    badge: "Demo profile",
    mode: "Online",
    availability: ["Tuesday", "Thursday"],
    image: null,
    rank: 27,
  },
  {
    id: "fahad-hussain",
    name: "Fahad Hussain",
    location: "Islamabad",
    sports: ["Football"],
    specialty: "Defending shape and transition play",
    rating: null,
    reviewCount: 0,
    price: 4000,
    reason: "Tactical football coaching for positioning, defensive shape and quick transitions.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Wednesday", "Friday"],
    image: null,
    rank: 28,
  },
  {
    id: "rabia-noor",
    name: "Rabia Noor",
    location: "Online",
    sports: ["Strength"],
    specialty: "Strength routines for busy beginners",
    rating: null,
    reviewCount: 0,
    price: 2300,
    reason: "Short online strength sessions with simple routines and clear weekly progression.",
    badge: "Demo profile",
    mode: "Online",
    availability: ["Monday", "Saturday"],
    image: null,
    rank: 29,
  },
  {
    id: "zeeshan-akram",
    name: "Zeeshan Akram",
    location: "Rawalpindi",
    sports: ["Tennis", "Badminton"],
    specialty: "Racket-sport footwork and consistency",
    rating: null,
    reviewCount: 0,
    price: 3400,
    reason: "Adaptable racket-sport coaching for movement, contact and rally consistency.",
    badge: "Demo profile",
    mode: "In person",
    availability: ["Friday", "Sunday"],
    image: null,
    rank: 30,
  },
];

const styleBySport: Record<Sport, string> = {
  Badminton: "Clear demonstrations, repeatable footwork patterns and rally-based progress.",
  Basketball: "Skill repetitions followed by realistic decisions and short competitive games.",
  Boxing: "Controlled technical rounds with safety, defense and confidence before intensity.",
  Cricket: "Simple technical cues, video feedback and game-like practice with a clear weekly goal.",
  Football: "Ball-heavy sessions that move from technique into realistic small-sided situations.",
  "Ice Hockey": "Fast skill blocks, positional scenarios and practical team-play feedback.",
  Running: "Sustainable progress through form cues, manageable volume and honest recovery checks.",
  Strength: "Measured progress, clear movement coaching and programs adapted to available equipment.",
  Swimming: "Calm pool instruction using short drills, breathing control and visible technique goals.",
  "Table Tennis": "High-repetition stroke work followed by spin-reading and point construction.",
  Tennis: "Technical foundations, purposeful drills and match situations without information overload.",
  Yoga: "Accessible movement sequences with patient cues and options for different mobility levels.",
};

export const demoCatalogDetailsByCoach: Record<string, { tags: string[]; audiences: string[]; levels: string[]; languages: string[] }> = {
  "ayesha-khan": { tags: ["Batting", "Beginner friendly"], audiences: ["Children", "Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "hamza-siddiqui": { tags: ["Serving", "Match preparation"], audiences: ["Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "sara-ahmed": { tags: ["Mobility", "Remote coaching"], audiences: ["Adults", "Seniors"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "zainab-malik": { tags: ["Water confidence", "Technique"], audiences: ["Children", "Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "omar-farooq": { tags: ["Home workouts", "Beginner friendly"], audiences: ["Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "bilal-raza": { tags: ["First touch", "Youth coaching"], audiences: ["Children", "Teenagers"], levels: ["Beginner", "Intermediate", "Advanced"], languages: ["English", "Urdu", "Punjabi"] },
  "danish-iqbal": { tags: ["Conditioning", "Footwork"], audiences: ["Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "hira-noor": { tags: ["Footwork", "Rally control"], audiences: ["Children", "Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "farhan-akram": { tags: ["Endurance", "Race preparation"], audiences: ["Adults"], levels: ["Beginner", "Intermediate", "Advanced"], languages: ["English", "Urdu"] },
  "mariam-shah": { tags: ["Ball handling", "Shooting"], audiences: ["Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "usman-tariq": { tags: ["Serving", "Rally consistency"], audiences: ["Teenagers", "Adults"], levels: ["Beginner", "Intermediate", "Advanced"], languages: ["English", "Urdu"] },
  "nadia-hussain": { tags: ["Mobility", "Older adults"], audiences: ["Adults", "Seniors"], levels: ["Beginner"], languages: ["English", "Urdu"] },
  "rida-aslam": { tags: ["Batting analysis", "Remote coaching"], audiences: ["Teenagers", "Adults"], levels: ["Intermediate", "Advanced"], languages: ["English", "Urdu"] },
  "sameer-qureshi": { tags: ["Conditioning", "Movement"], audiences: ["Teenagers", "Adults"], levels: ["Intermediate", "Advanced"], languages: ["English", "Urdu"] },
  "iqra-javed": { tags: ["Fundamentals", "Beginner friendly"], audiences: ["Children", "Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "haris-mehmood": { tags: ["Bowling", "Match preparation"], audiences: ["Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "sana-rauf": { tags: ["Rally consistency", "Footwork"], audiences: ["Children", "Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "ahmed-nawaz": { tags: ["Home workouts", "Beginner friendly"], audiences: ["Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "mehwish-iqbal": { tags: ["Water confidence", "Technique"], audiences: ["Children", "Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "talha-ansari": { tags: ["First touch", "Youth coaching"], audiences: ["Children", "Teenagers"], levels: ["Beginner", "Intermediate", "Advanced"], languages: ["English", "Urdu"] },
  "kiran-shah": { tags: ["Footwork", "Rally control"], audiences: ["Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "saad-mirza": { tags: ["Ball handling", "Shooting"], audiences: ["Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "anum-tariq": { tags: ["Mobility", "Remote coaching"], audiences: ["Adults", "Seniors"], levels: ["Beginner"], languages: ["English", "Urdu"] },
  "waleed-khan": { tags: ["Defense", "Conditioning"], audiences: ["Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "komal-aziz": { tags: ["Endurance", "Race preparation"], audiences: ["Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
  "rehan-malik": { tags: ["Serving", "Spin reading"], audiences: ["Teenagers", "Adults"], levels: ["Intermediate", "Advanced"], languages: ["English", "Urdu"] },
  "alina-qureshi": { tags: ["Batting analysis", "Remote coaching"], audiences: ["Teenagers", "Adults"], levels: ["Intermediate", "Advanced"], languages: ["English", "Urdu"] },
  "fahad-hussain": { tags: ["Positioning", "Match preparation"], audiences: ["Teenagers", "Adults"], levels: ["Intermediate", "Advanced"], languages: ["English", "Urdu"] },
  "rabia-noor": { tags: ["Beginner friendly", "Home workouts"], audiences: ["Adults"], levels: ["Beginner"], languages: ["English", "Urdu"] },
  "zeeshan-akram": { tags: ["Footwork", "Rally consistency"], audiences: ["Children", "Teenagers", "Adults"], levels: ["Beginner", "Intermediate"], languages: ["English", "Urdu"] },
};

const trainingAreaByCoach: Record<string, { area: string; coordinates: Coach["coordinates"] }> = {
  "ayesha-khan": { area: "Gulberg", coordinates: [74.3507, 31.5204] },
  "hamza-siddiqui": { area: "Clifton", coordinates: [67.0332, 24.8143] },
  "sara-ahmed": { area: "Online", coordinates: null },
  "zainab-malik": { area: "DHA", coordinates: [74.4069, 31.4697] },
  "omar-farooq": { area: "Online", coordinates: null },
  "bilal-raza": { area: "DHA Phase 5", coordinates: [74.4454, 31.4632] },
  "danish-iqbal": { area: "Gulshan-e-Iqbal", coordinates: [67.0971, 24.9207] },
  "hira-noor": { area: "Model Town", coordinates: [74.3242, 31.4805] },
  "farhan-akram": { area: "F-8", coordinates: [73.0377, 33.7105] },
  "mariam-shah": { area: "PECHS", coordinates: [67.0611, 24.8718] },
  "usman-tariq": { area: "Johar Town", coordinates: [74.2728, 31.4694] },
  "nadia-hussain": { area: "Online", coordinates: null },
  "rida-aslam": { area: "Online", coordinates: null },
  "sameer-qureshi": { area: "North Nazimabad", coordinates: [67.0425, 24.9418] },
  "iqra-javed": { area: "I-8", coordinates: [73.1137, 33.6659] },
  "haris-mehmood": { area: "G-11", coordinates: [73.0363, 33.6844] },
  "sana-rauf": { area: "Gulberg", coordinates: [74.3587, 31.5204] },
  "ahmed-nawaz": { area: "Online", coordinates: null },
  "mehwish-iqbal": { area: "F-10", coordinates: [73.0315, 33.6992] },
  "talha-ansari": { area: "Bahria Town", coordinates: [73.1114, 33.4959] },
  "kiran-shah": { area: "DHA", coordinates: [67.0556, 24.799] },
  "saad-mirza": { area: "E-11", coordinates: [72.9886, 33.7018] },
  "anum-tariq": { area: "Online", coordinates: null },
  "waleed-khan": { area: "Model Town", coordinates: [74.3239, 31.4834] },
  "komal-aziz": { area: "Jilani Park", coordinates: [74.334, 31.5466] },
  "rehan-malik": { area: "Satellite Town", coordinates: [73.0544, 33.6422] },
  "alina-qureshi": { area: "Online", coordinates: null },
  "fahad-hussain": { area: "F-8", coordinates: [73.0398, 33.7102] },
  "rabia-noor": { area: "Online", coordinates: null },
  "zeeshan-akram": { area: "Saddar", coordinates: [73.0526, 33.5969] },
};

const illustrativeSportImages: Record<string, string> = {
  Badminton: "/images/coach-hira.jpg",
  Basketball: "/images/coach-usman.jpg",
  Boxing: "/images/coach-mariam.jpg",
  Cricket: "/images/coach-ayesha.jpg",
  Football: "/images/coach-danish.jpg",
  Running: "/images/coach-nadia.jpg",
  Strength: "/images/coach-sara.jpg",
  Swimming: "/images/coach-farhan.jpg",
  "Table Tennis": "/images/coach-iqra.jpg",
  Tennis: "/images/coach-hamza.jpg",
  Yoga: "/images/coach-rida.jpg",
};

export function illustrativeImageForSports(sports: readonly string[]) {
  return sports.map((sport) => illustrativeSportImages[sport]).find(Boolean) ?? "/images/hero-training.jpg";
}

export const coaches: Coach[] = baseCoaches.map((coach) => {
  const primarySport = coach.sports[0];
  const durableDetails = demoCatalogDetailsByCoach[coach.id];
  return {
    ...coach,
    tags: durableDetails.tags,
    badge: "Demo profile",
    image: coach.image ?? illustrativeImageForSports(coach.sports),
    rating: null,
    reviewCount: 0,
    lessonCount: 0,
    credentials: [],
    offersOnline: coach.mode.includes("Online"),
    offersInPerson: coach.mode.includes("In person"),
    ...trainingAreaByCoach[coach.id],
    bio: `${coach.name} helps athletes build useful, repeatable skills without making sessions feel intimidating. ${coach.reason}`,
    experience: "Illustrative coaching background",
    coachingStyle: styleBySport[primarySport],
    languages: durableDetails.languages,
    audiences: durableDetails.audiences,
    levels: durableDetails.levels,
    lessonPlan: [
      {
        title: "Goal check and warm-up",
        description: "A short check-in, safe movement preparation and one clear goal for the session.",
      },
      {
        title: "Focused skill work",
        description: `Demonstrations and repeatable drills focused on ${coach.specialty.toLowerCase()}.`,
      },
      {
        title: "Guided practice and next steps",
        description: "Apply the skill in a realistic exercise, then leave with focused feedback and a simple practice target.",
      },
    ],
    isDemo: true,
    faqs: [
      {
        question: "Is this suitable for someone new to the sport?",
        answer: "Yes. Sessions are adapted to the athlete's current ability, confidence and goals.",
      },
      {
        question: "What should I bring?",
        answer: "Bring water, comfortable sportswear and any personal equipment you already use. Venue-specific requirements are confirmed before the lesson.",
      },
      {
        question: "How long is each lesson?",
        answer: "The listed price covers one 60-minute lesson unless a different duration is agreed during booking.",
      },
    ],
  };
});

export const allSports: Sport[] = Array.from(new Set(coaches.flatMap((coach) => coach.sports))).sort();

export const formatCoachPrice = (price: number) => `Rs ${price.toLocaleString("en-PK")}`;
